
name: Build OpenAI EXE

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Build EXE
      run: |
        sh build_scripts/openai/windows_build.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: gpt-computer-assistant-openai
        path: dist/*